from time import sleep
import random
main=input("enter a mobile number: ")
main = int(main)
print("searchibg for " + main)
print(main + " successfully found")
mlw=input("send virus [y/n] ")
if mlw=="n":
  print("starting exit: ")
  print("[@---------]")
  sleep(1)
  print("[@@--------]")
  sleep(1)
  print("[@@@-------]")
  sleep(1)
  print("[@@@@------]")
  sleep(1)
  print("[@@@@@-----]")
  sleep(1)
  print("[@@@@@@----]")
  sleep(1)
  print("[@@@@@@@---]")
  sleep(1)
  print("[@@@@@@@@--]")
  sleep(1)
  print("[@@@@@@@@@@]")
  sleep(1)
  print("Exited successfull")
elif mlw=="y":
  print("waiting for viral codes to respond: ")
  sleep(3)
  print("[@---------]")
  sleep(2)
  print("[@@--------]")
  sleep(2)
  print("[@@@-------]")
  sleep(2)
  print("[@@@@------]")
  sleep(2)
  print("code slow! ")
  sleep(5)
  print("code required, again! ") 
  sleep(3)
  print("[@@@@@-----]")
  sleep(1)
  print("[@@@@@@----]")
  sleep(1)
  print("[@@@@@@@---]")
  sleep(1)
  print("[@@@@@@@@--]")
  sleep(1)
  print("[@@@@@@@@@@]")
  sleep(1)
  print("virus successfully sent to " + main)
  kill=input("kill all files [y/n] ")
  if kill=="n":
    print("Exiting")
    print("[@---------]")
    sleep(1)
    print("[@@--------]")
    sleep(1)
    print("[@@@-------]")
    sleep(1)
    print("[@@@@------]")
    sleep(1)
    print("[@@@@@-----]")
    sleep(1)
    print("[@@@@@@----]")
    sleep(1)
    print("[@@@@@@@---]")
    sleep(1)
    print("[@@@@@@@@--]")
    sleep(1)
    print("[@@@@@@@@@@]")
    sleep(1)
    print("exited, virus deleted")
  elif kill=="y":
    print("checking(this might take a while)")
    sleep(5)
    print("all files and data found")
    sleep(3)
    lower = "abcdefghijklmnopg.nstuvwxyz"
    upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    numbers = "0123456789"
    symbols = "_"

    all = lower+upper+numbers+symbols

    length=5
    pad=" " . join(random.sample(all, length))
    print("deleting large file "+pad)
    sleep(1)
    print("deleted file: "+pad+"1")
    sleep(1)
    print("deleted file: "+pad+"2")
    sleep(1)
    print("deleted file: "+pad+"3") 
    sleep(1)
    print("deleted file: "+pad+"4")
    sleep(1)
    print("deleted file: "+pad+"5")
    
    
    print("deleted file: "+pad+"6")
    
    
    print("deleted file: "+pad+"8")
    sleep(1)
    
    print("deleted file: "+pad+"9")
    sleep(1)
    
    print("deleted file: "+pad+"10")
    sleep(1)
    print("deleted file: "+pad+"10A")
    
    print("deleted file: "+pad+"10B")
    
    print("deleted file: "+pad+"10C")
    sleep(2)
    print("deleting other files from all drives")
    print("deleted files numbered from: ")
    sleep(2)
    for i in range(30000):
      print(i)
      print(i)
    print("all files deleted successfully") 
